### ISSUE TITLE
findlib dependencies are not correct

### ISSUE THREAD

**Issue by agarwal** [0xffea/ocaml-redis#24]
```
# #require "redis.lwt";;
Error: Reference to undefined global `Re_str'
```

I believe the correct fix is to update `META` to make the sub-package depend on the parent package, i.e. the `requires` field of the `redis.lwt` sub-package should have `redis` added to it. I'm not submitting a pull request because I'm not certain of this.

**Comment by Leonidas-from-XIV** [comment]
In my OASIS generated META file from the current release this is set (`requires = "lwt.unix lwt redis"`) and the call you cite works just fine.

**Comment by agarwal** [comment]
You're right. I was pinned and I see now that the bug was introduced in e491b3a5a934f532a6b4459b5cc752bf1f709b3c.
