### ISSUE TITLE
Redis_sync and Redis_lwt behave differently

### ISSUE THREAD

**Issue by agarwal** [0xffea/ocaml-redis#25]
The lwt client can't ping the server while the blocking version can. I did it several times and this happened reproducibly.

```
# let host = "123.45.0.1";;
# let port = 6379;;

# Redis_lwt.Client.(with_connection {host; port} ping);;
- : bool = false

# Redis.Redis_sync.Client.(with_connection {host; port} ping);;
- : bool = true
```

**Comment by SumitPadhiyar** [comment]
@agarwal I'm not able to reproduce this bug. Do you remember, whether this bug was reproducible on every run or occasionally while stress testing? Also, any special setup to reproduce this?

**Comment by agarwal** [comment]
@SumitPadhiyar Hi. It happened every time. It was not just during stress testing.

**Comment by c-cube** [comment]
works for me as well (adding `Lwt_main.run` of course).

**Comment by c-cube** [comment]
works for me as well (adding `Lwt_main.run` of course).

**Comment by SumitPadhiyar** [comment]
> works for me as well (adding `Lwt_main.run` of course).

@c-cube does this mean you were able to reproduce this bug?

**Comment by c-cube** [comment]
Sorry, I mean, I got `true` from the ping command even with lwt.
