### ISSUE TITLE
examples/subscribe_lwt.ml does not compile

### ISSUE THREAD

**Issue by acs1** [0xffea/ocaml-redis#32]
The example subscribe_lwt.ml does not compile.

```
File "subscribe_lwt.ml", line 21, characters 64-77:
Error: This expression has type reply list IO.stream
       but an expression was expected of type
         [> `Bulk of bytes option
          | `Error of bytes
          | `Int of int
          | `Status of bytes ]
         list Lwt_stream.t
```

**Comment by aluuu** [comment]
Hi, @acs1 

Thanks for reporting this issue. I've fixed it in #33. 

I think it may affect not only our examples, so I decided to release [0.3.1](https://github.com/ocaml/opam-repository/pull/6978). It will be available soon.
