### ISSUE TITLE
ocaml-redis is not (Lwt-) thread safe

### ISSUE THREAD

**Issue by talex5** [0xffea/ocaml-redis#42]
Trying to invoke Redis from two Lwt threads at the same time causes it to fail. This test program demonstrates the problem:

```
open Lwt.Infix

let threads = 2
let iters = 10
let payload_size = 1000000

let () = Sys.set_signal Sys.sigpipe Sys.Signal_ignore

let total = ref 0

let make_thread c i =
  let key = Printf.sprintf "<%d>" i in
  let rec aux = function
    | 0 -> Lwt.return ()
    | n ->
      if n mod 100 = 0 then Printf.printf "%s%!" key;
      let base = Random.int 26 in
      let data = String.init payload_size (fun x -> Char.chr (((x + base) mod 26) + 65)) in
      Redis_lwt.Client.set c key data >>= fun _ ->
      let b = Redis_lwt.Client.get c key in
      b >>= fun b ->
      assert (b = Some data);
      total := !total + 1;
      aux (n - 1)
  in
  aux iters

let () =
  Lwt_main.run begin
    Redis_lwt.Client.connect {Redis_lwt.Client.host = "127.0.0.1"; port = 6379} >>= fun c ->
    Array.init threads (make_thread c) |> Array.to_list |> Lwt.join
  end;
  Printf.printf "Total tests: %d\n%!" !total
```

Expected output:

```
Total tests: 20
```

Actual output:

```
Fatal error: exception Redis.Client.Make(IO).Error("ERR unknown command '$3$3$1000000'")
```

The problem doesn't appear if the number of threads is reduced to one, or if the payload is smaller. Tested on OS X, using the current Git version of redis (with #41).

**Comment by hcarty** [comment]
The issue here is that a single connection is not safe to use across threads, not that the library as a whole is unsafe when used across threads, correct? If you use one connection per thread does the example still fail?

**Comment by hcarty** [comment]
Each time I've used ocaml-redis it's been against a pool of Redis connections so I hadn't run into this issue - it's good to know that it exists.

**Comment by talex5** [comment]
BTW, I'm using this to add a Redis backend to ocaml-session: https://github.com/inhabitedtype/ocaml-session/pull/8

The lack of pipelining means it needs to do 2 round-trips however, even with a pool:

https://github.com/inhabitedtype/ocaml-session/pull/8/files#diff-efa23988caced58cb7845d35f3652005R48

(using two connections for this could lead to deadlock)

**Comment by shinzui** [comment]
Is this still an issue? Is this library safe to use in production?

**Comment by rgrinberg** [comment]
Yes it's safe. Though it's advised to build a connection pool on top of it.

**Comment by shinzui** [comment]
Thank you. Shouldn't the issue be closed and your recommendation added to the readme?

**Comment by c-cube** [comment]
Please re-open if necessary.
