### ISSUE TITLE
Tests should be disabled by default

### ISSUE THREAD

**Issue by talex5** [0xffea/ocaml-redis#43]
ocaml-redis's opam file specifies tests that test against the user's local Redis installation (and fail if they don't have one). This probably not a good thing to do automatically, as people will assume tests won't use their existing database.

Also, it prevents testing programs that depend on ocaml-redis, because `opam -t mypackage` (very stupidly) also tests all of `mypackages`'s dependencies (see https://github.com/ocaml/opam/issues/2190).

PR for the opam file in opam-repository: https://github.com/ocaml/opam-repository/pull/8030

**Comment by samoht** [comment]
Note: the behaviour of `-t` should be fixed in opam 2.0 (/cc @altgr to check that it is actually the case :-))
