### ISSUE TITLE
Document how to set up a pool of connections

### ISSUE THREAD

**Issue by talex5** [0xffea/ocaml-redis#44]
https://github.com/0xffea/ocaml-redis/issues/42#issuecomment-264908397 suggests using a pool of Redis connections. However, it's not clear how to set this up.

e.g. I can do

    Lwt_pool.create 4 (fun () -> Redis_lwt.Client.connect addr)

But if Redis is restarted (or the connection is otherwise lost) then the broken connections are never removed from the pool and the client never recovers. It's not obvious to me how to write the validate function for this:

    let validate conn = ?? in
    Lwt_pool.create 4 ~validate (fun () -> Redis_lwt.Client.connect addr)

I currently have a hack using `~check` instead to discard the connection of any operation that fails, but it might be better to check first. In any case, it would be good to include some recommendation in the docs.

Thanks,

**Comment by NightBlues** [comment]
```
let redis_pool size conn_spec = Lwt_pool.create size
    ~validate:(fun Redis_lwt.Client.{fd;_} ->
        match Lwt_unix.state fd with
        | Lwt_unix.Opened -> Lwt.return_true
        | _ -> Lwt.return_false)
    (fun () -> Redis_lwt.Client.connect conn_spec)
```

**Comment by NightBlues** [comment]
Well, I now understand the trouble. :( Redis protocol seems to be bad designed, for example if you do `blpop` with big timeout you can not interrupt operation if for example your lwt thread waiting for respnse was canceled.
```
utop # #require "lwt_ppx";;
utop # #require "ppx_deriving.std";;
utop # let%lwt conn = Redis_lwt.Client.connect {host="localhost";port=6379} in
  let pp_res_th =
      let%lwt res = Redis_lwt.Client.blpop conn ["testkey"] 10 in
      Lwt_io.printf "res = %s\n" ([%show: (string * string) option] res)
  in
  let sleep_th = Lwt_unix.sleep 2.0 in
  (* wait for 2 seconds and cancel pp_res_th thread *)
  let%lwt () = Lwt.pick [pp_res_th; sleep_th] in
  (* connection will be invalid for 8 seconds, so our next command is ignored *)
  let%lwt res2 = Redis_lwt.Client.get conn "otherkey" in
  Lwt_io.printf "res2 = %s\n" ([%show: string option] res2);;
```
