### ISSUE TITLE
FTBFS with OCaml 4.06

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [0xffea/ocaml-redis#54]
Due to OCaml 4.06 setting `safe-string` as default, the compilation fails:

```
File "src/client.ml", line 107, characters 26-30:
Error: This expression has type bytes but an expression was expected of type
         string
```

There are two possibilities: either fix the semantics to accept `string` where `string` makes sense or set the build system to use `-no-safe-string`.

**Comment by 0xffea** [comment]
Should be fixed now. Thanks for reporting.

**Comment by Leonidas-from-XIV** [comment]
Thanks! Looks like that happened in e2ce9197707b0ff8544b5b7499ac006acc97161f. Good.
