### ISSUE TITLE
Version without batteries

### ISSUE THREAD

**Issue by rgrinberg** [0xffea/ocaml-redis#6]
Would it be possible to remove the batteries dependency from this client?

**Comment by aluuu** [comment]
Hello.

I have done [some work](https://github.com/aluuu/ocaml-redis/commits/remove-batteries) around your issue.
It would be great if you and @0xffea will review my branch before merge with `master`.

**Comment by rgrinberg** [comment]
@aluuu Sure I'll review it. Could you make a PR first though? Would be easier to leave comments in a PR.

**Comment by aluuu** [comment]
I've changed version of package to 0.2.1 which would contain last changes and created corresponding [pull request](https://github.com/ocaml/opam-repository/pull/3356) in `opam-repository`. 
Hope it will be available soon through OPAM.
