### ISSUE TITLE
new maintainer(s)?

### ISSUE THREAD

**Issue by c-cube** [0xffea/ocaml-redis#62]
hi, it seems this is not very actively maintained, I could help if you want :slightly_smiling_face:

**Comment by 0xffea** [comment]
Yes, Aleksandr Dinu and I don't have much time anymore. So you can become the new main maintainer.

**Comment by c-cube** [comment]
Ok, let's do this then. Any guidelines / wishes on the becoming of the lib?

**Comment by 0xffea** [comment]
You should have push access now.

**Comment by c-cube** [comment]
Thanks! :slightly_smiling_face: 

I'm going to tackle issues, add some tests, etc.

**Comment by c-cube** [comment]
I can't seem to be able to modify travis setup or the settings regarding documentation, though :/
