### ISSUE TITLE
Fuzzing connect throws Unix.EADDRNOTAVAIL

### ISSUE THREAD

**Issue by SumitPadhiyar** [0xffea/ocaml-redis#76]
Fuzzing simple program that connects to a local redis instance and sents ping command results in Unix.EADDRNOTAVAIL exception. Here is the program,

```open Lwt.Infix
let host = "127.0.0.1" and  port = 6379

let () =

  let open Redis_lwt.Client in 
  Crowbar.(add_test ~name:"ping property" [Crowbar.const 1] (fun i -> 

      Lwt_main.run  begin
        (connect {host=host; port=port})
        >>= fun conn -> Redis_lwt.Client.ping conn
        >>= fun result -> disconnect conn
      end

    ))
```
The corresponding exception
```
Unix.Unix_error(Unix.EADDRNOTAVAIL, "connect", "")
    Raised at file "src/unix/lwt_main.ml", line 38, characters 15-22
    Called from file "src/core/crowbar.ml", line 355, characters 16-19
```

**Comment by c-cube** [comment]
I don't have a crowbar/AFL setup at the moment. Can you make a (hopefully small) repro of the bug that just requires redis?

**Comment by SumitPadhiyar** [comment]
Weirdly on removing crowbar and executing in a loop with a  script, does not result in crash.

```
open Lwt.Infix
let host = "127.0.0.1" and  port = 6379

let () =
  let open Redis_lwt.Client in 
  Lwt_main.run  begin
    (connect {host=host; port=port})
    >>= fun conn -> ping conn
    >>= fun result -> disconnect conn
  end
```
Script 
```
#!/bin/bash
for i in {1..30000}
do
    ./a.out
done
```
Still it reliably crashes with Crowbar. Compiling with crowbar and passing infinite test flag(-i) to binary, reproduces the crash. No need of AFL. Interestingly it crashes exactly around after 23k tests. FYI, ulimit shows open files allowed to be 65535.

**Comment by c-cube** [comment]
So the bug is actually caused by exhaustion of file descriptors? I'm not sure how crowbar works on a binary but it may run several instances of `Lwt_main.run` simultaneously, maybe?

A possible way to test for that hypothesis is to use a `Lwt_pool` or something similar to limit the number of simultaneous connectoins.

**Comment by SumitPadhiyar** [comment]
> So the bug is actually caused by exhaustion of file descriptors?
>
Doesn't look like, I tried reducing open files hard limit to 1024. Still it crashed only around 23k. Same with increasing open files limit to 65535. May be internally ocaml-redis is leaking some fd. 

>  I'm not sure how crowbar works on a binary but it may run several instances of `Lwt_main.run` simultaneously, maybe?
>
Crowbar does not execute tests parallely. So at a time there is only one instance of ``` Lwt_main.run``` running.  

> A possible way to test for that hypothesis is to use a `Lwt_pool` or something similar to limit the number of simultaneous connectoins.
> 
I think there's only one connection at a time, as tests are executed sequentially and connection is explicitly disconnected everytime. But still, I'll try this out.

**Comment by SumitPadhiyar** [comment]
I got hold of the problem. The crash was arising out of exhaustion of ephemeral port range. Setting ```net.ipv4.tcp_tw_reuse = 1``` did the trick. Hence closing the issue.
