### ISSUE TITLE
No implementations found for Re_str, uuidm packages

### ISSUE THREAD

**Issue by SumitPadhiyar** [0xffea/ocaml-redis#77]
I'm trying to compile a simple program with build from [commit ](https://github.com/0xffea/ocaml-redis/tree/bbba72f06412ceb69e0b8a17cba00c92eda8f29c). Corresponding program
```
open Lwt.Infix
let host = "127.0.0.1" and  port = 6379

let () =

  let open Redis_lwt.Client in 
      Lwt_main.run  begin
        (connect {host=host; port=port})
        >>= fun conn -> Redis_lwt.Client.ping conn
        >>= fun result -> disconnect conn
      end
```
Compliing program give this error.
```
findlib: [WARNING] Interface mutex.cmi occurs in several directories: /home/skip/.opam/4.08.0+afl/lib/redis, /home/skip/.opam/4.08.0+afl/lib/ocaml/threads
File "ocaml_redis_25.ml", line 1:
Error: No implementations provided for the following modules:
         Re_str referenced from /home/skip/.opam/4.08.0+afl/lib/redis/redis_lwt.cmxa(Utils)
         Uuidm referenced from /home/skip/.opam/4.08.0+afl/lib/redis/redis_lwt.cmxa(Mutex)
```
Re_str and uuitdm are indeed installed on my system.
```
re                      1.9.0       RE is a regular expression library for OCaml
uuidm                   0.9.7       Universally unique identifiers (UUIDs) for OCaml
```

**Comment by c-cube** [comment]
That's pretty strange, since `redis-lwt` depends on `redis` which does indicate its deps on re and uuidm. What's the command you use to compile, and does it mention these libraries?

**Comment by SumitPadhiyar** [comment]
I'm building locally by
```
./configure --enable-lwt
make
make install
```
I can see in `_oasis`, redis depends on both re and uuidm. In fact make does specify packages while compiling.

**Comment by c-cube** [comment]
you might want to check what version/commit you're using. On the last few releases it's built using dune, not oasis.

**Comment by SumitPadhiyar** [comment]
Yes, I'm actually building `redis` from an old commit(bbba72f06412ceb69e0b8a17cba00c92eda8f29c) that uses oasis.

**Comment by c-cube** [comment]
maybe it's a missing `Library` or whatever in the `_oasis` file?
Anyway, we don't support oasis versions anymore, what's your use case? :)

**Comment by SumitPadhiyar** [comment]
I wanted to reproduce [this](https://github.com/0xffea/ocaml-redis/issues/25) bug. So I was building locally from the commit before the patch.

**Comment by c-cube** [comment]
Ah, makes sense. You can just link `re` and `uuidm` by hand maybe, if you're just trying to make it work for a repro.
