### ISSUE TITLE
Issue with set+expire

### ISSUE THREAD

**Issue by kohlivarun5** [0xffea/ocaml-redis#78]
We recently upgraded to 0.4 and found an issue with set+expire usage in [this](https://github.com/0xffea/ocaml-redis/commit/508685dd28cd8759f706f334f064d5bfd2a3085d) commit for cache.ml

It seems to give a protocol error when the data length exceeds 100k. Reverting the change to do set >= expire seems to restore behavior and works for large strings

**Comment by c-cube** [comment]
do you have a (reasonably simple) reproduction? I don't see anything obviously bad in the code. Is it exactly 100kb?

**Comment by kohlivarun5** [comment]
Something of this form :


```ocaml
module IntStr_params = struct 
  type key = int 
  type data = string 

  let cache_key = string_of_int 
  let cache_expiration = Some 200

  let data_of_string (str:string) = (str:data)
  let string_of_data (data:data) = (data:string)
end

module IntStrCache 
  : (Redis.S.Cache with 
        module Params = IntStr_params and 
        module IO = Redis_lwt.IO and 
        module Client = Redis_lwt.Client)
  = Redis.Cache.Make(Redis_lwt.IO)(Redis_lwt.Client)(IntStr_params)


(* get connection from somewhere *) 

  let value = String.make 200000 'c' in 
  let _ = 
    Lwt_result.bind_lwt conn (fun conn -> IntStrCache.set conn 1 value)
    |> Lwt_main.run

```

It is not exactly 100kb, but I think I found somewhere around 171k was the breaking point

Exception was:
`Redis.Client.Common(IO).Redis_error("ERR Protocol error: expected '$', got 'X'")`

**Comment by c-cube** [comment]
I tried this, on the branch `wip-78` with `dune exec test/reg_78.exe`, and got no failure. Could it be a setting in your redis instance?

`redis-cli monitor` shows the key being added with an `EX 200` at the end, and the key properly expires after that.

**Comment by kohlivarun5** [comment]
hmm, thanks for looking at it. I’ll try the test locally and see if it is something else and report back

**Comment by kohlivarun5** [comment]
I was able to replicate the test you had on our redis. Seems related to how our distributed redis is setup. 

When I run local redis-server the test passes, when I point to the remote server, it gives error.

Either way, created https://github.com/0xffea/ocaml-redis/pull/79 in case it might be useful. Might be better than doing pipelining anyways

**Comment by c-cube** [comment]
does #79 solve the issue on your cluster?

**Comment by kohlivarun5** [comment]
Yes, #79 solves the issues for us
