### ISSUE TITLE
redis.cmxa can't reference Utils

### ISSUE THREAD

**Issue by pzread** [0xffea/ocaml-redis#9]
Sorry, I'm not very familiar with ocaml. When I build my code with
ocamlfind opt -o db -linkpkg -package redis.lwt db.ml

It says:
Error: No implementations provided for the following modules:
         Utils referenced from /home/user/.opam/system/lib/redis/redis.cmxa(Redis)

Maybe it's something wrong in the build configuration?

My code:
let () = let conn = Redis_lwt.Client.connect {host="127.0.0.1"; port=6379} in ()

**Comment by aluuu** [comment]
Hello.

There's a bug with forgotten Utils module in _oasis file. I've updated package version to 0.2.3 and it will be available in OPAM soon.

Thank you for reporting.

**Comment by pzread** [comment]
Thanks for fix, it's OK now.
